version: '3.1'

volumes:
  vol_DEVICE_DATA:
  vol_DEVICE_DATA_IMAGES:

services:
  remarkableviewer:
    container_name: remarkableviewer
    volumes:
      # - ./configs/.ssh:/home/node/.ssh
      - vol_DEVICE_DATA:/home/node/RemarkableViewer/DEVICE_DATA
      - vol_DEVICE_DATA_IMAGES:/home/node/RemarkableViewer/DEVICE_DATA_IMAGES
    build:
      context: "."
      dockerfile: dockerfiles/RemarkableViewer/Dockerfile
    user: "node"
    working_dir: /home/node/RemarkableViewer
    environment:
      - NODE_ENV=production
    ports:
      - 3100:3100
    restart: on-failure
    command: "nodemon"
    # command: "tail -f /dev/null"
